# Generated by Django 3.2.3 on 2021-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, default='Document469210212579326', max_length=120, unique=True, verbose_name='document_name')),
                ('doc', models.TextField(verbose_name='document')),
                ('about', models.TextField(blank=True, default='', help_text='Write some description about the document')),
                ('doc_img', models.ImageField(default='doc_image.png', upload_to='', verbose_name='document_img')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
