# Generated by Django 3.2.3 on 2021-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210516_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, default='Document663392586173731', max_length=120, unique=True, verbose_name='document_name')),
                ('doc', models.TextField(verbose_name='document')),
                ('about', models.TextField(blank=True, default='', help_text='Write some description about the document')),
                ('doc_img', models.ImageField(default='/static/doc_image.png', upload_to='', verbose_name='document_img')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
