# Generated by Django 3.2.3 on 2021-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20210516_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_img',
            field=models.ImageField(default='static/doc_image.png', upload_to='', verbose_name='document_img'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(blank=True, default='Document456562979138996', max_length=120, unique=True, verbose_name='document_name'),
        ),
    ]
