# Generated by Django 3.2.3 on 2021-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20210516_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(blank=True, default='Document827054900791798', max_length=250, unique=True, verbose_name='document_name'),
        ),
    ]
