# Generated by Django 3.2.3 on 2021-05-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_alter_document_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.TextField(help_text='you cannot a emoji', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(blank=True, default='Document882298612088860', max_length=250, unique=True, verbose_name='document_name'),
        ),
    ]
