# Generated by Django 3.2.3 on 2021-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20210518_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.TextField(help_text='you cannot add an emoji', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(blank=True, default='Document263927125693828', max_length=250, unique=True, verbose_name='document_name'),
        ),
    ]
